- hosts: east
  become: true
  tasks:
    - name: copy files
      copy:
        src: /mnt/artefact/spring-petclinic-2.5.0-SNAPSHOT.jar
        dest: /tmp
    - name:  copy another files
      copy:
        src: /var/lib/jenkins/workspace/build-job/ansible/
        dest: /tmp  
    - name: docker down
      shell: docker-compose -f /tmp/docker-compose.yml down
    - name: docker build 
      shell: docker-compose -f /tmp/docker-compose.yml build
    - name: docker up 
      shell: docker-compose -f /tmp/docker-compose.yml up -d
