- hosts: east
  become: true
  tasks:
    - name: copy files
      copy:
        src: /mnt/artefact/*.jar
        dest: /tmp
    - name: docker
      shell: docker-compose -f /tmp/docker-compose.yml up -d
             java -Dspring.profiles.active=mysql -jar /tmp/spring-petclinic-2.5.0-SNAPSHOT.jar &