- hosts: east
  become: true
  tasks:
   - name: copy files
      copy:
        src: /mnt/artefact/*.jar
        dest: /tmp
    - name: docker up 
      shell: docker-compose -f /tmp/docker-compose.yml up -d
